apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts

helmCharts:
# Temporal helm chart
  - name: temporal
    releaseName: temporal
    valuesFile: temporal-values.yaml
    includeCRDs: false
    version: 0.19.0
    namespace: default

# Jenkins helm chart
  - name: jenkins
    releaseName: jenkins
    valuesFile: jenkins-values.yaml
    includeCRDs: false
    version: 4.2.19
    namespace: default